# This is a basic workflow to help you get started with Actions
# Examples from:
# https://github.com/marketplace/actions/setup-node-js-environment
# https://docs.github.com/en/actions/guides/building-and-testing-python
# https://github.com/marketplace/actions/build-and-push-docker-images

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        architecture:
          - x64
        #  - arm64
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🥾
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - # https://github.com/marketplace/actions/python-setup-rye
        name: Python Setup Rye
        uses: eifinger/setup-rye@v4.2.6
        with:
          # enable-cache: true
          version: 'latest'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip setuptools wheel
      #     pip install -r _b00t_/python.🐍/src/requirements.txt

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      #     check-latest: true
      # # - run: npm install
      # # - run: npm test

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: user/app:latest
      #     secrets: |
      #       GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

